// ชุดที่ 13 — แก้ไขโจทย์ในไฟล์นี้
window.SET_18 = [
    { id: 854, question: "How does MAC learning function on a switch?", options: ["broadcasts frames to all ports without queueing", "adds unknown source MAC addresses to the address table", "sends a retransmission request when a new frame is received", "sends frames with unknown destinations to a multicast group"], answer: 1 },
    { id: 855, question: "A client experiences slow throughput from a server that is directly connected to the core switch in a data center. A network engineer finds minimal latency on connections to the server, but data transfers are unreliable, and the output of the show interfaces counters errors command shows a high FCS-Err count on the interface that is connected to the server. What is the cause of the throughput issue?", options: ["high bandwidth usage", "a physical cable fault", "a speed mismatch", "a cable that is too long"], answer: 1 },
    { id: 858, question: "A network administrator wants the syslog server to filter incoming messages into different files based on their importance. Which filtering criteria must be used?", options: ["level", "message body", "process ID", "facility"], answer: 0 },
    { id: 859, question: "Why is a first-hop redundancy protocol implemented?", options: ["to protect against default gateway failures", "to prevent loops in a network", "to enable multiple switches to operate as a single unit", "to provide load-sharing for a multilink segment"], answer: 0 },
    { id: 862, question: "A network engineer must migrate a router loopback interface to the IPv6 address space. If the current IPv4 address of the interface is 10.54.73.1/32, and the engineer configures IPv6 address 0:0:0:0:0:ffff:36:4901, which prefix length must be used?", options: ["/64", "/96", "/124", "/128"], answer: 3 },
    { id: 863, question: "Which IPsec transport mode encrypts the IP header and the payload?", options: ["pipe", "control", "transport", "tunnel"], answer: 3 },
    { id: 864, question: "A Cisco engineer at a new branch office is configuring a wireless network with access points that connect to a controller that is based at corporate headquarters. Wireless client traffic must terminate at the branch office and access-point survivability is required in the event of a WAN outage. Which access point mode must be selected?", options: ["Lightweight with local switching disabled", "Local with AP fallback enabled", "OfficeExtend with high availability disabled", "FlexConnect with local switching enabled"], answer: 3 },
    { id: 885, question: "What are two purposes of HSRP? (Choose two.)", options: ["It groups two or more routers to operate as one virtual router.", "It improves network availability by providing redundant gateways.", "It passes configuration information to hosts in a TCP/IP network.", "It helps hosts on the network to reach remote subnets without a default gateway.", "It provides a mechanism for diskless clients to autoconfigure their IP parameters during boot."], answer: [0,1] },
    { id: 886, question: "Why implement VRRP?", options: ["To provide end users with a virtual gateway in a multivendor network.", "To leverage a weighting scheme to provide uninterrupted service.", "To detect link failures without the overhead of Bidirectional Forwarding Detection.", "To hand over to end users the autodiscovery of virtual gateways."], answer: 0 },
    { id: 871, question: "Which interface enables communication between a program on the controller and a program on the networking devices?", options: ["northbound interface", "software virtual interface", "southbound interface", "tunnel interface"], answer: 1 },
    { id: 883, question: "What is the function of off-the-shelf switches in a controller-based network?", options: ["providing a central view of the deployed network", "forwarding packets", "making routing decisions", "setting packet-handling policies"], answer: 3 },
    { id: 884, question: "What is the operating mode and role of a backup port on a shared LAN segment in Rapid PVST+?", options: ["forwarding mode and provides the lowest cost path to the root bridge for each VLAN", "learning mode and provides the shortest path toward the root bridge handling traffic away from the LAN", "blocking mode and provides an alternate path toward the designated bridge", "listening mode and provides an alternate path toward the root bridge"], answer: 2 },    
    { id: 889, question: "What does traffic shaping do?", options: ["It modifies the QoS attributes of a packet", "It queues excess traffic", "It organizes traffic into classes", "It sets QoS attributes within a packet"], answer: 0 },   
    { id: 890, question: "Which architecture is best for small offices with minimal wireless needs and no central management?", options: ["cloud-based AP", "split MAC", "autonomous AP", "mesh network"], answer: 2 },    
    { id: 891, question: "Which channel-group mode must be configured when multiple distribution interfaces connected to a WLC are bundled?", options: ["Channel-group mode passive", "Channel-group mode on", "Channel-group mode desirable", "Channel-group mode active"], answer: 1 },    
    { id: 892, question: "What are two facts that differentiate optical fiber cabling from copper cabling? (Choose two.)", options: ["It has a greater sensitivity to changes in temperature and moisture", "It carries signals for longer distances", "It carries electrical current further distances for PoE devices", "It is less expensive when purchasing patch cables", "It provides greater throughput options"], answer: [0,1] },   
    { id: 894, question: "What is the difference between an IPv6 link-local address and a unique local address?", options: ["The scope of an IPv6 link-local address is limited to a loopback address, and an IPv6 unique local address is limited to a directly attached interface.", "The scope of an IPv6 link-local address can be used throughout a company site or network, but an IPv6 unique local address is limited to a loopback address.", "The scope of an IPv6 link-local address is global, but the scope of an IPv6 unique local address is limited to a loopback address.", "The scope of an IPv6 link-local address is limited to a directly attached interface, but an IPv6 unique local address is used throughout a company site or network."], answer: 1 },    
    { id: 895, question: "What is a characteristic of RSA?", options: ["It uses preshared keys for encryption", "It requires both sides to have identical keys", "It is a private-key encryption algorithm", "It is a public-key cryptosystem"], answer: 3 },    
    { id: 897, question: "Which protocol is used in Software Defined Access (SDA) to provide a tunnel between two edge nodes in different fabrics?", options: ["Generic Router Encapsulation (GRE)", "Virtual Local Area Network (VLAN)", "Virtual Extensible LAN (VXLAN)", "Point-to-Point Protocol"], answer: 2 },    
    { id: 899, question: "What is used to identify spurious DHCP servers?", options: ["DHCPREQUEST", "DHCPDISCOVER", "DHCPACK", "DHCPOFFER"], answer: 3 },    
    { id: 900, question: "An engineer must configure a core router with a floating static default route to the backup router at 10.200.0.2. Which command meets the requirements?", options: ["ip route 0.0.0.0 0.0.0.0 10.200.0.1", "ip route 0.0.0.0 0.0.0.0 10.200.0.2 floating", "ip route 0.0.0.0 0.0.0.0 10.200.0.2", "ip route 0.0.0.0 0.0.0.0 10.200.0.2 10"], answer: 3 }
                
    ];
    