// ชุดที่ 13 — แก้ไขโจทย์ในไฟล์นี้
window.SET_17 = [
    { id: 801, question: "What is the role of community strings in SNMP operations?", options: ["It serves as a sequence tag on SNMP traffic messages.", "It serves as a password to protect access to MIB objects.", "It passes the Active Directory username and password that are required for device access.", "It translates alphanumeric MIB output values to numeric values."], answer: 1 },
    { id: 802, question: "What differentiates the Cisco OfficeExtend AP mode from FlexConnect AP mode?", options: ["FlexConnect allows a personal SSID to be configured on the AP, and personal SSIDs are not supported with OfficeExtend.", "OfficeExtend does not support DTLS tunneling of traffic to the WLC, and FlexConnect tunnels traffic to the WLC with DTLS.", "OfficeExtend tunnels all traffic through the WLC, and FlexConnect terminates client traffic at the AP switch port.", "FlexConnect must be deployed behind a router that NATs the client traffic, and OfficeExtend uses public IP sources."], answer: 2 },
    { id: 803, question: "What determines the sequence in which materials are planned during the material requirements planning (MRP) run?", options: ["The control parameters of the MRP run", "The creation date of the materials", "The low-level code of the materials", "The replenishment lead time of the materials"], answer: 2 },
    { id: 808, question: "What is a feature of WPA2?", options: ["802.1x authentication", "preshared key", "TKIP/MIC encryption", "small Wi-Fi application"], answer: 0 },
    { id: 809, question: "Which set of actions satisfies the requirement for multifactor authentication?", options: ["The user enters a user name and password, and then clicks a notification in an authentication app on a mobile device.", "The user swipes a key fob, then clicks through an email link.", "The user enters a PIN into an RSA token, and then enters the displayed RSA key on a login screen.", "The user enters a user name and password, and then re-enters the credentials on a second screen."], answer: 0 },
    { id: 815, question: "SIP-based Call Admission Control must be configured in the Cisco WLC GUI. SIP call-snooping ports are configured. Which two actions must be completed next? (Choose two.)", options: ["Set the QoS level to silver or greater for voice traffic.", "Set the QoS level to platinum for voice traffic.", "Enable Media Session Snooping on re WLAN.", "Enable traffic shaping for the LAN interface of the WLC.", "Configure two different QoS roles for data and voice traffic."], answer: [3, 4] },
    { id: 816, question: "What is the role of nonoverlapping channels in a wireless environment?", options: ["to reduce interference", "to allow for channel bonding", "to stabilize the RF environment", "to increase bandwidth"], answer: 0 },
    { id: 817, question: "Why is UDP more suitable than TCP for applications that require low latency, such as VoIP?", options: ["UDP reliably guarantees delivery of all packets and TCP drops packets under heavy load.", "TCP sends an acknowledgment for every packet that is received and UDP operates without acknowledgments.", "UDP uses sequencing data for packets to arrive in order and TCP offers the capability to receive packets in random order.", "TCP uses congestion control for efficient packet delivery and UDP uses flow control mechanisms for the delivery of packets."], answer: 1 },
    { id: 819, question: "Which AP mode serves as the primary hub in a point-to-multipoint network topology?", options: ["FlexConnect", "SE-Connect", "bridge", "local"], answer: 2 },
    { id: 821, question: "Which two statements distinguish authentication from accounting? (Choose two.)", options: ["Only authentication records the duration of a user's connection.", "Only authentication supports user-activity audits.", "Only authentication provides supporting information for billing users.", "Only authentication challenges users for their credentials and returns a response.", "Only authentication validates 'who you are.'"], answer: [3, 4] },
    { id: 822, question: "What is a valid IPv6 address record in DNS?", options: ["A", "MX", "AAAA", "CNAME"], answer: 2 },
    { id: 825, question: "What must be considered before deploying virtual machines?", options: ["location of the virtual machines within the data center environment", "whether to leverage VSM to map multiple virtual processors to two or more virtual machines", "resource limitations, such as the number of CPU cores and the amount of memory", "support for physical peripherals, such as monitors, keyboards, and mice"], answer: 2 },
    { id: 830, question: "Which interface is used for out-of-band management on a WLC?", options: ["dynamic", "service port", "virtual", "management"], answer: 1 },
    { id: 833, question: "Which Windows command is used instead of the route print command to display the contents of the IP routing table?", options: ["netstat -n", "ipconfig", "ifconfig", "netstat -r"], answer: 3 },
    { id: 834, question: "Which type of address is shared by routers in a HSRP implementation and used by hosts on the subnet as their default gateway address?", options: ["multicast address", "loopback IP address", "virtual IP address", "broadcast address"], answer: 2 },
    { id: 835, question: "When an access point is seeking to join a wireless LAN controller, which message is sent to the AP-Manager interface?", options: ["Discovery response", "DHCP request", "DHCP discover", "Discovery request"], answer: 3 },
    { id: 837, question: "What are two benefits for using private IPv4 addressing? (Choose two.)", options: ["They alleviate the shortage of public IPv4 addresses.", "They supply redundancy in the case of failure.", "They offer Internet connectivity to endpoints on private networks.", "They allow for Internet access from IoT devices.", "They provide a layer of security from Internet threats."], answer: [0, 4] },
    { id: 838, question: "Which interface or port on the WLC is the default for in-band device administration and communications between the controller and access points?", options: ["virtual interface", "management interface", "console port", "service port"], answer: 1 },
    { id: 844, question: "Which command configures the Cisco WLC to prevent a serial session with the WLC CLI from being automatically logged out?", options: ["config sessions maxsessions 0", "config sessions timeout 0", "config serial timeout 0", "config serial timeout 9800"], answer: 1 },
    { id: 845, question: "Which benefit does Cisco DNA Center provide over traditional campus management?", options: ["Cisco DNA Center leverages SNMPv3 for encrypted management, and traditional campus management uses SNMPv2.", "Cisco DNA Center automates HTTPS for secure web access, and traditional campus management uses HTTP.", "Cisco DNA Center leverages APIs, and traditional campus management requires manual data gathering.", "Cisco DNA Center automates SSH access for encrypted entry, and SSH is absent from traditional campus management."], answer: 1 },
    { id: 846, question: "What is a similarity OM3 and OM4 fiber optical cable?", options: ["Both have a 62.5 micron core diameter.", "Both have a 50 micron core diameter.", "Both have a 100 micron core diameter.", "Both have a 9 micron core diameter."], answer: 1 },
    { id: 849, question: "A wireless access point is needed and must meet these requirements: 'zero-touch' deployed and managed by a WLC, process only real-time MAC functionality, used in a split-MAC architecture. Which access point type must be used?", options: ["autonomous", "lightweight", "mesh", "cloud-based"], answer: 1 },
               
    ];
    