// ชุดที่ 13 — แก้ไขโจทย์ในไฟล์นี้
window.SET_21 = [
    { id: 1003, question: "What is the definition of backdoor malware?", options: ["malicious code that is installed onto a computer to allow access by an unauthorized user", "malicious code with the main purpose of downloading other malicious code", "malicious program that is used to launch other malicious programs", "malicious code that infects a user machine and then uses that machine to send spam"], answer: 0 },
    { id: 1004, question: "What is the RFC 4627 default encoding for JSON text?", options: ["UCS-2", "UTF-8", "Hex", "GB18030"], answer: 1 },
    { id: 1006, question: "A network architect is deciding whether to implement Cisco autonomous access points or lightweight access points. Which fact about firmware updates must the architect consider?", options: ["Unlike lightweight access points, which require redundant WLCs to support firmware upgrades, autonomous access points require only one WLC.", "Unlike autonomous access points, lightweight access points store a complete copy of the current firmware for backup.", "Unlike lightweight access points, autonomous access points can recover automatically from a corrupt firmware update.", "Unlike autonomous access points, lightweight access points require a WLC to implement remote firmware updates."], answer: 3 },
    { id: 1008, question: "What does a switch do when it receives a frame whose destination MAC address is missing from the MAC address table?", options: ["It floods the frame unchanged across all remaining ports in the incoming VLAN.", "It appends the table with a static entry for the MAC and shuts down the port.", "It updates the CAM table with the destination MAC address of the frame.", "It changes the checksum of the frame to a value that indicates an invalid frame."], answer: 0 },
    { id: 1003, question: "What is the definition of backdoor malware?", options: ["malicious code that is installed onto a computer to allow access by an unauthorized user", "malicious code with the main purpose of downloading other malicious code", "malicious program that is used to launch other malicious programs", "malicious code that infects a user machine and then uses that machine to send spam"], answer: 0 },
    { id: 1004, question: "What is the RFC 4627 default encoding for JSON text?", options: ["UCS-2", "UTF-8", "Hex", "GB18030"], answer: 1 },
    { id: 1006, question: "A network architect is deciding whether to implement Cisco autonomous access points or lightweight access points. Which fact about firmware updates must the architect consider?", options: ["Unlike lightweight access points, which require redundant WLCs to support firmware upgrades, autonomous access points require only one WLC.", "Unlike autonomous access points, lightweight access points store a complete copy of the current firmware for backup.", "Unlike lightweight access points, autonomous access points can recover automatically from a corrupt firmware update.", "Unlike autonomous access points, lightweight access points require a WLC to implement remote firmware updates."], answer: 3 },
    { id: 1008, question: "What does a switch do when it receives a frame whose destination MAC address is missing from the MAC address table?", options: ["It floods the frame unchanged across all remaining ports in the incoming VLAN.", "It appends the table with a static entry for the MAC and shuts down the port.", "It updates the CAM table with the destination MAC address of the frame.", "It changes the checksum of the frame to a value that indicates an invalid frame."], answer: 0 },
    { id: 1011, question: "Which remote access protocol provides unsecured remote CLI access?", options: ["console", "Telnet", "Bash", "SSH"], answer: 1 },
    { id: 1013, question: "What is the main difference between traditional networks and controller-based networking?", options: ["Controller-based networks increase TCO for the company, and traditional networks require less investment.", "Controller-based networks provide a framework for innovation, and traditional networks create efficiency.", "Controller-based networks are open for application requests, and traditional networks operate manually.", "Controller-based networks are a closed ecosystem, and traditional networks take advantage of programmability."], answer: 2 },
    { id: 1017, question: "Which type of DNS record is used to specify the mail server responsible for accepting email messages on behalf of a recipient’s domain?", options: ["MX record", "TXT record", "A record", "SRV record"], answer: 2 },
    { id: 1019, question: "Which group of channels in the 802.11b/g/n/ac/ax 2.4 GHz frequency Bands are nonoverlapping channels?", options: ["channels 1, 5, and 10", "channels 1, 6, and 11", "channels 1, 5, and 11", "channels 1, 6, and 10"], answer: 1 },
    { id: 1020, question: "Which signal frequency appears 60 times per minute?", options: ["1 Hz signal", "1 GHz signal", "60 Hz signal", "60 GHz signal"], answer: 1 },
    { id: 1023, question: "What is the purpose of configuring different levels of syslog for different devices on the network?", options: ["to rate-limit messages for different severity levels from each device", "to set the severity of syslog messages from each device", "to identify the source from which each syslog message originated", "to control the number of syslog messages from different devices that are stored locally"], answer: 1 },
    { id: 1025, question: "What is the difference between controller-based networks and traditional networks as they relate to control-plane and/or data-plane functions?", options: ["Controller-based networks centralize all important data-plane functions, and traditional networks distribute data-plane functions.", "Controller-based networks centralize all important control-plane functions, and traditional networks distribute control-plane functions.", "Traditional networks centralize all important control-plane functions, and controller-based networks distribute control-plane functions.", "Traditional networks centralize all important data-plane functions, and controller-based networks distribute data-plane functions."], answer: 0 },
    { id: 1027, question: "Which solution is appropriate when mitigating password attacks where the attacker was able to sniff clear-text password of the system administrator?", options: ["A next-generation firewall to keep stateful packet inspection", "Multifactor authentication using two separate authentication sources", "ACL to restrict incoming Telnet sessions \"admin\" accounts", "IPS with a block list of known attack vectors"], answer: 0 },
    { id: 1028, question: "Company has decided to require multifactor authentication for all systems. Which set of parameters meets the requirement?", options: ["A personal 10-digit PIN and RSA certificate", "Complex password and personal 10-digit PIN", "Password of 8 to 15 characters and personal 12-digit PIN", "Fingerprint scanning and facial recognition"], answer: 0 },
    { id: 1030, question: "Which IP header field is changed by a Cisco device when QoS marking is enabled?", options: ["Header Checksum", "Type of service", "DSCP", "ECN"], answer: 1 },
    { id: 1035, question: "What is a function of Cisco Advanced Malware Protection for a Next-Generation IPS?", options: ["authorizing potentially compromised wireless traffic", "inspecting specific files and file types for malware", "authenticating end users", "URL filtering"], answer: 1 },
    { id: 1036, question: "What are two examples of multifactor authentication? (Choose two.)", options: ["single sign-on", "unique user knowledge", "passwords that expire", "soft tokens", "shared password responsibility"], answer: [1,3] },
    { id: 1038, question: "Which enhancements were implemented as part of WPA3?", options: ["802.1x authentication and AES-128 encryption", "TKIP encryption improving WEP and per-packet keying", "AES-64 personal mode and AES-128 in enterprise mode", "forward secrecy and SAE in personal mode for secure initial key exchange"], answer: 3 },
    { id: 1039, question: "A switch is forwarding a frame out of all interfaces except the interface that received the frame. What is the technical term for this process?", options: ["ARP", "Multicast", "CDP", "Flooding"], answer: 3 },
    { id: 1041, question: "What is the advantage of separating the control plane from the data plane within an SDN network?", options: ["decreases overall network complexity", "limits data queries to the control plane", "reduces cost", "offloads the creation of virtual machines to the data plane"], answer: 0 },
    { id: 1042, question: "How does encryption protect the wireless network?", options: ["via integrity checks to identify wireless forgery attacks in the frame", "via specific ciphers to detect and prevent zero-day network attacks", "via an algorithm to change wireless data so that only the access point and client understand it", "via a policy to prevent unauthorized users from communicating on the wireless network"], answer: 2 },
    { id: 1043, question: "Which type of IPv4 address must be assigned to a server to protect it from external access and allow only internal users access while restricting internet access?", options: ["global unicast", "public", "private", "multicast"], answer: 2 },
    { id: 1045, question: "Why would VRRP be implemented when configuring a new subnet in a multivendor environment?", options: ["when a gateway protocol is required that support more than two Cisco devices for redundancy", "to enable normal operations to continue after a member failure without requiring a change in a host ARP cache", "to ensure that the spanning-tree forwarding path to the gateway is loop-free", "to interoperate normally with all vendors and provide additional security features for Cisco devices"], answer: 0 },
    { id: 1049, question: "Which two IPv6 addresses are used to provide connectivity between two routers on a shared link? (Choose two)", options: ["::ffff:1014:1011/96", "2001:7011046:1111::/64", "jf06bb43cd4dd111bbf02 4545234d", "2002:5121204b:1111::1/64", "FF02::0/104"], answer: 1 },
    { id: 1050, question: "What is a difference between an IPv6 multicast address and an IPv6 anycast address?", options: ["A packet sent to an IPv6 multicast address is delivered to one or more destinations at once, but a packet sent to an IPv6 anycast address is routed to the closest interface with that address.", "An IPv6 multicast address uses the prefix 2002::/15 and forwards to one destination, and an IPv6 anycast address uses the prefix ff00::/8 and forwards to any destination in a group.", "IPv6 multicast addresses are used to transition from IPv4 to IPv6, and IPv6 anycast addresses are used for address aggregation in an IPv6-only environment.", "An IPv6 multicast address is assigned to numerous interfaces within a subnet, but an IPv6 anycast address is used for a predefined group of nodes in an all-IPv6 routers group."], answer: 0 },
                        

];
    