
window.SET_22 = [
    { id: 1151, question: "What is a similarity between global and unique local IPv6 addresses?", options: ["They are allocated by the same organization.", "They are routable on the global internet.", "They use the same process for subnetting.", "They are part of the multicast IPv6 group type."], answer: 2 },
    { id: 1152, question: "Which key function is provided by the data plane?", options: ["Making routing decisions", "Originating packets", "Forwarding traffic to the next hop", "Exchanging routing table data"], answer: 2 },
    { id: 1153, question: "What is the main purpose of SSH management access?", options: ["To support DES 56-bit and 3DES (168-bit) ciphers", "To enable secured access to the inbound management interface", "To validate management access with username and domain name only", "To allow passwords protected with HTTPS encryption to be sent"], answer: 1 },
    { id: 1156, question: "Which interface is used to send traffic to the destination network?", options: ["G0/23", "G0/3", "G0/16", "G0/6"], answer: 3 },
    { id: 1157, question: "What is a function of a Next-Generation IPS?", options: ["Integrates with a RADIUS server to enforce Layer 2 device authentication rules", "Serves as a controller within a controller-based network", "Makes forwarding decisions based on learned MAC addresses", "Correlates user activity with network events"], answer: 3 },
    { id: 1163, question: "How is AI used to identify issues within network traffic?", options: ["It exclusively predicts device malfunctions.", "It enhances data packet delivery speeds.", "It simplifies traffic route mapping.", "It analyzes patterns for anomaly detection."], answer: 3 },
    { id: 1165, question: "Which role does AI play in monitoring network data flow?", options: ["It analyzes patterns for anomaly detection.", "It exclusively predicts device malfunctions.", "It simplifies traffic route mapping.", "It enhances data packet delivery speeds."], answer: 0 },
    { id: 1171, question: "Which action implements physical access control as part of the security program of an organization?", options: ["configuring a password for the console port", "configuring enable passwords on network devices", "backing up syslogs at a remote location", "setting up IP cameras to monitor key infrastructure"], answer: 3 },
    { id: 1177, question: "What is a characteristic of private IPv4 addressing?", options: ["alleviates the shortage of IPv4 addresses", "reduces the forwarding table on network routers", "enables secure connectivity over the internet", "used as the NAT outside global IP address"], answer: 2 },
    { id: 1181, question: "Which interface is used to send traffic to the destination network?", options: ["G0/16", "G0/15", "G0/13", "G0/12"], answer: 1 },
    { id: 1182, question: "Why would a network administrator choose to implement RFC 1918 address space?", options: ["to route traffic on the internet", "to provide flexibility in the IP network design", "to provide overlapping address space with another network", "to limit the number of hosts on the network"], answer: 1 },
    { id: 1186, question: "How are API keys used to enforce rate limiting?", options: ["to specify the type of data format the client prefers to receive", "to define the network path the API request should take", "to encrypt data sent in the API request", "to uniquely identify each client application"], answer: 3 },
    { id: 1188, question: "In which way does a spine-and-leaf architecture allow for scalability in a network when additional access ports are required?", options: ["A spine switch and a leaf switch are added with redundant connections between them.", "A spine switch is added with at least 40GB uplinks.", "A leaf switch is added with a single connection to a core spine switch.", "A leaf switch is added with connections to every spine switch."], answer: 3 },
    { id: 1189, question: "What are two behaviors of a point-to-point WAN topology? (Choose two.)", options: ["It uses a single router to route traffic between sites.", "It leverages a dedicated connection.", "It connects remote networks through a single line.", "It delivers redundancy between the central office and branch offices.", "It provides direct connections between each router in the topology."], answer: [1,2] },
    { id: 1190, question: "What is the maximum length of characters used in an SSID?", options: ["16", "32", "48", "64"], answer: 1 },
    { id: 1191, question: "Which two northbound APIs are found in a software-defined network? (Choose two.)", options: ["OpenFlow", "REST", "OpFlex", "SOAP", "NETCONF"], answer: [1,3] },
    { id: 1192, question: "Which security element uses a combination of one-time passwords, a login name, and a personal smartphone?", options: ["software-defined segmentation", "multifactor authentication", "attribute-based access control", "rule-based access control"], answer: 1 },
    { id: 1196, question: "What is a function of a northbound API in an SDN environment?", options: ["It supports distributed processing for configuration.", "It relies on global provisioning and configuration.", "It upgrades software and restores files.", "It provides orchestration and network automation services."], answer: 3 },
    { id: 1197, question: "Which cloud-provided service allows an organization to install its own operating system on a virtual machine?", options: ["platform-as-a-service", "software-as-a-service", "infrastructure-as-a-service", "network-as-a-service"], answer: 2 },
    { id: 1199, question: "Which protocol should be used to transfer large files on a company intranet that allows UDP 69 through the firewall?", options: ["FTP", "TFTP", "REST API", "SMTP"], answer: 0 },


];
    